# Generated by Django 3.1.2 on 2020-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocable',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English')], default='EN', max_length=2),
        ),
    ]
