# Generated by Django 3.1.2 on 2020-11-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_vocable_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vocable',
        ),
        migrations.DeleteModel(
            name='Vocabulary',
        ),
    ]
