# Generated by Django 3.1.2 on 2020-11-30 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=9999)),
                ('language', models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish')], max_length=2)),
                ('target_language', models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish')], max_length=2)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('translated_value', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=2)),
                ('target_language', models.CharField(max_length=2)),
                ('success_counter', models.IntegerField(default=0)),
                ('failed_counter', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabularies.vocabulary')),
            ],
        ),
    ]
