# Generated by Django 3.1.2 on 2020-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocable',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
