# Generated by Django 3.1.2 on 2020-12-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocable',
            name='language',
        ),
        migrations.RemoveField(
            model_name='vocable',
            name='target_language',
        ),
    ]
