# Generated by Django 3.1.2 on 2020-11-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0002_auto_20201113_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='target_language',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish')], max_length=2),
        ),
    ]
