# Generated by Django 3.1.2 on 2020-11-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0003_auto_20201113_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocable',
            name='vocabulary_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vocabularies.vocabulary'),
            preserve_default=False,
        ),
    ]
