# Generated by Django 3.1.2 on 2020-11-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_vocable_vocabulary_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocable',
            old_name='vocabulary_id',
            new_name='vocabulary',
        ),
        migrations.AddField(
            model_name='vocable',
            name='failed_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocable',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vocable',
            name='success_counter',
            field=models.IntegerField(default=0),
        ),
    ]
