# Generated by Django 3.1.2 on 2020-11-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_vocable_vocabulary_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocable',
            old_name='vocabulary_id',
            new_name='vocabulary',
        ),
    ]
