# Generated by Django 3.1.2 on 2020-11-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=9999)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('vocabularies', models.ManyToManyField(to='vocabularies.Vocabulary')),
            ],
        ),
    ]
