# Generated by Django 3.1.2 on 2020-11-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_vocable_vocabulary_id'),
        ('cards', '0003_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnset',
            name='vocabularies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vocabularies.vocabulary'),
            preserve_default=False,
        ),
    ]
