# Generated by Django 3.1.2 on 2020-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_vocable_vocabulary_id'),
        ('cards', '0004_learnset_vocabularies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnset',
            name='vocabularies',
        ),
        migrations.AddField(
            model_name='learnset',
            name='vocabularies',
            field=models.ManyToManyField(to='vocabularies.Vocabulary'),
        ),
    ]
