# Generated by Django 3.1.2 on 2020-11-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20201128_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
